import XCTest
@testable import StringsFileLibTests

XCTMain([
    testCase(DisplayEmptyLineTests.allTests),
    testCase(DisplayErrorTests.allTests),
    testCase(ExitWithErrorTests.allTests),
    testCase(LoadInputFilesTests.allTests),
    testCase(LogTests.allTests),
    testCase(MergeTests.allTests),
    testCase(ParseFilesContentsTests.allTests),
    testCase(ParseLinesTests.allTests),
    testCase(PrintToStdErrTests.allTests),
    testCase(ReadFileTests.allTests),
    testCase(SortStringPairsTests.allTests),
    testCase(SubstringToFirstOccurrenceTests.allTests),
    testCase(ToDelimitedStringFromCamelCaseTests.allTests),
    testCase(ToDictionaryFromStringPairsTests.allTests),
    testCase(ToExitStatusFromErrorTests.allTests),
    testCase(ToLinesFromStringPairTests.allTests),
    testCase(ToLinesFromStringPairsTests.allTests),
    testCase(VerboseTests.allTests),
    testCase(WarningTests.allTests),
    testCase(WriteLinesTests.allTests),
    testCase(FileErrorTests.allTests),
    testCase(DictionaryTests.allTests),
    testCase(FileHandleTests.allTests),
    testCase(ConflictMarkerInfoTests.allTests),
    testCase(MergeInfoTests.allTests),
    testCase(StringPairTests.allTests),
    testCase(CustomErrorTests.allTests),
    testCase(NameDisplayableTests.allTests),
])
